services:
  client:
    build:
      context: ../../client
      dockerfile: Dockerfile
    container_name: client
    restart: always
    ports:
      - "${PORT}:80"
    environment:
      - NODE_ENV=${NODE_ENV}
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    env_file:
      - ../../client/.env
